### ISSUE TITLE
`table_oid` type is `int` but probably should be `oid`?

### ISSUE THREAD

**Issue by michelp** [supabase/supa_audit#12]
https://github.com/supabase/supa_audit/blob/d62b8c1be84d90ff4ddb096620e4ab6414801703/supa_audit--0.1.0.sql#L38

`oid`s are unsigned 32 bit integers, but `int` is signed, so this can cause issues where a table's oid could be stored as a negative value in this column if it exceeds the signed positive int maximum.

**Comment by olirice** [comment]
resolved by #13
