### ISSUE TITLE
Add to audit table username 

### ISSUE THREAD

**Issue by overlinejota** [supabase/supa_audit#19]
Supa_audit is fantastict!, but, to my total satisfaction, I miss being able to have a field with the username that performs the crud operation
My postgrsql knowledge is poor, sorry if i ask something impossible or trivial.
Would it be possible to add the username that performs the operation (insert, update, delete)?
Thanks

**Comment by olirice** [comment]
it depends where your user_id is coming from

- if you're on the supabase platform, 2 additional columns are enabled by default that track the user's id and the user's role

- if `user_id` is in the table you're auditing
``` alter table audit.record_version add column user_id bigint default (coalesce(record, old_record) ->> 'user_id'); ```

will add a user_id column and track it in the table

- if you mean the SQL `current_user` you could extend the trigger to track it.

- if the concept of a user_id comes from the application thats connecting to the database, netcraft posted an option for adding it here https://news.ycombinator.com/item?id=30615470

**Comment by overlinejota** [comment]
Thank you Oliver
