### ISSUE TITLE
Uppercase table name.

### ISSUE THREAD

**Issue by overlinejota** [supabase/supa_audit#20]
I can't enable uppercase table.
`select audit.enable_tracking('public.**Account'**::regclass);`
I've tried everything but I can't get it to work.
Thank you

**Comment by olirice** [comment]
this should work
```sql
select 'public."Account"'::regclass
```

**Comment by overlinejota** [comment]
I'm sorry but I can't.
`select audit.enable_tracking('public.**Account'**::regclass);`
don't work, but
`select audit.enable_tracking('public.**account'**::regclass);`
It works well.
(of course, the table has the name in uppercase or lowercase in each case)
