### ISSUE TITLE
Comparison with Audit trigger 91plus

### ISSUE THREAD

**Issue by swazrgb** [supabase/supa_audit#21]
Could you provide a comparison with https://wiki.postgresql.org/wiki/Audit_trigger_91plus which has been my go-to from the postgres wiki for quite some time? Also, perhaps this project could be added linked to from https://wiki.postgresql.org/wiki/Audit_trigger

**Comment by olirice** [comment]
I'm not familiar with that project but it looks like the main differences are that it uses hstore for storage (vs jsonb) and also tracks info about the statement that caused the change
