### ISSUE TITLE
Error with Postgres 10 in Windows when Insert and Delete

### ISSUE THREAD

**Issue by rgfpy** [supabase/supa_audit#23]
# Bug report

## Describe the bug
Error when insert not found old statement
Error when delete not found new statement

## To Reproduce

Steps to reproduce the behavior, please provide code snippets or a repository:

1. Go to '…'
2. Click on '…'
3. Scroll down to '…'

## Expected behavior
Insert to audit table

## Screenshots
https://ibb.co/K2NYy0d

create schema if not exists audit;

## System information

Use Postgres from EDB Installator

- OS: Windows
- Browser (if applies) [e.g. chrome, safari]
- Version of supabase-js: xxx
- Version of Node.js: xxx

**Comment by rgfpy** [comment]
I fixed with declare conditions to declare set old and new record id and the final section to return the old or new depending with tg_op

**Comment by olirice** [comment]
sorry to hear you had trouble working with the extension.

I see that you're running postgres 10. `supa_audit` supports postgres 13 and above so its likely that you're bumping into a compatibility error. If you think the issue is not related to the postgres version, please try to reproduce on pg 13 or 14 and let me know if it is still preset

thanks!

**Comment by rgfpy** [comment]
Ok, thank you for you response! 
Regards!

**Comment by rgfpy** [comment]
Yes in PG10 need more some mods with old and new data references

**Comment by mustajarvi** [comment]
Got it. Wondering if there were something hindering the use with PG 11. Sorry for issue hijack, but figured it was close enough. Might create a separate issue and put that question there.

**Comment by olirice** [comment]
>  Wondering if there were something hindering the use with PG 11

Not currently, I just ran the test suite against Postgres 11 and everything passed so you're probably good to go but keep in mind that future updates might not be compatible
