### ISSUE TITLE
Default for ts column

### ISSUE THREAD

**Issue by jmadren** [supabase/supa_audit#24]
Why do you have the default for column ts set to "now() at time zone 'utc'"? This causes it to store the current local time as if it were UTC, which throws the time off if you're not really in the UTC/GMT time zone.

The timestamptz data type already takes care of converting whatever time it is given to UTC for storage. And it is automatically converted to the local time zone when output. So the default should just be "now()" for it to capture the truly correct time.

**Comment by olirice** [comment]
sorry for the delay, its been a busy week

when you're right, you're right!
I didn't realize `at time zone 'utc'` returns a `timestamp without time zone`

thanks for reporting
