### ISSUE TITLE
Should `search_path` be set due to use of `SECURITY DEFINER`

### ISSUE THREAD

**Issue by msdrigg** [supabase/supa_audit#29]
# Chore

## Describe the chore

I was just reading the [documentation for CREATE FUNCTION in postgres](https://www.postgresql.org/docs/9.3/sql-createfunction.html), and I see the following section:

> ### Writing SECURITY DEFINER Functions Safely
>
> Because a SECURITY DEFINER function is executed with the privileges of the user that created it, care is needed to ensure that the function cannot be misused. For security, [search_path](https://www.postgresql.org/docs/9.3/runtime-config-client.html#GUC-SEARCH-PATH) should be set to exclude any schemas writable by untrusted users. 

## Additional context

I was just wondering if `search_path` should be set for the `SECURITY_DEFINER` functions in `supa_audit`. I am not a postgres expert, so if this isn't necessary for this repository, I would like to learn why not.

**Comment by olirice** [comment]
interesting stuff

From that same doc:
```
This prevents malicious users from creating objects that mask objects used by the function
```
so the risk is that the user could manipulate a schema they control, that is on the search path, to obscure the table that we want to audit

Something like
```sql
create schema malicious;
create schema public;

create table public.account ....;

-- malicious user wants to hide 'public.account'
create table malicious.account ...;

-- if our search path looked like this
set search_path = 'malicious,public';

-- and the admin didn't specify the schema when auditing a table
select audit.enable_tracking('account'::regclass);
```

then the admin might think they're auditing `public.account` when they're actually auditing `malicious.account`.

It seems like a low risk but I'll leave this open and add an explicit `search_path` next time we do an update

thanks for raising the question
