### ISSUE TITLE
make install fails

### ISSUE THREAD

**Issue by MichaelDBA** [supabase/supa_audit#30]
I am able to do the **make**, but when I do **make install** it fails with:
```
/usr/bin/mkdir -p '/usr/pgsql-12/lib'
/usr/bin/mkdir -p '/usr/pgsql-12/share/extension'
/usr/bin/mkdir -p '/usr/pgsql-12/share/extension'
/usr/bin/install -c -m 755  supa_audit.so '/usr/pgsql-12/lib/supa_audit.so'
/usr/bin/install -c -m 644 .//supa_audit.control '/usr/pgsql-12/share/extension/'
/usr/bin/install -c -m 644 .//supa_audit--0.1.0--0.2.0.sql .//supa_audit--0.2.2--0.2.3.sql .//supa_audit--0.2.1--0.2.2.sql .//supa_audit--0.2.3.sql .//supa_audit--0.2.0--0.2.1.sql  '/usr/pgsql-12/share/extension/'
/usr/bin/mkdir -p '/usr/pgsql-12/lib/bitcode/supa_audit'
/usr/bin/mkdir -p
/usr/bin/mkdir: missing operand
Try '/usr/bin/mkdir --help' for more information.
make: *** [/usr/pgsql-12/lib/pgxs/src/makefiles/pgxs.mk:234: install] Error 1

```
Interesting though, it does successfully put the extension in the target PG extension directory.

Also, you may want to add some requisites for this, namely, that the PG development package needs to be installed first.

Also, consider adding documentation to configure your PG environment before doing the make and make install. Need to set path = **target pg bin directory:$PATH**.  This will fix references to **pg_config** as well.

**Comment by olirice** [comment]
I was not able to recreate this error

Here's the output for me (macOS 12.2.1, postgres 14.2 installed via brew)

<img width="914" alt="Screen Shot 2022-04-18 at 9 45 26 AM" src="https://user-images.githubusercontent.com/12958657/163825572-b97fd57b-5459-4374-8e05-9d81add066d0.png">


Please note that `supa_audit` is a postgres 13+ extension only. If you could create a reproducible case against 13+ in a docker container (or other reproducible env) I'd be happy to help you debug


> Also, you may want to add some requisites for this, namely, that the PG development package needs to be installed first.

The readme assumes some familiarity with installing postgres extensions and skips the default requirements but if you'd like to update the readme with more complete install instructions I'm game to merge it!

**Comment by MichaelDBA** [comment]
Wow, didn't know it is only for PG13!  Why is that?

**Comment by olirice** [comment]
it is currently compatible with 12 but we're targeting 13+ to keep the maintenance burden down for future updates

**Comment by MichaelDBA** [comment]
What breaks in v11 or v10?

**Comment by MichaelDBA** [comment]
I actually tested it successfully for v11.  It does break for v10 though.

Also, please add as a pre-requisite for installing that you need the PG development package installed beforehand.  For CentOS it is something like this: postgresql13-devel.x86_64

I would suggest you make it supportable for V11+ since it works for all of them now.

Back to the original issue, make install error:
There is no error when compiling for PG v13, just for v11 and v12.  Although both v11 and v12 work since it successfully copied the extension to the PG extension directory.

just that weird error where it is trying to do another mkdir -p <without a directory specification>

**Comment by olirice** [comment]
> I would suggest you make it supportable for V11+ since it works for all of them now.

you're welcome to use it on 11 and 12 at your own risk but we're going to stick with only officially supporting 13+ to avoid unknown issues like the `make install` problem you're currently seeing against pg 12

**Comment by MichaelDBA** [comment]
wish I was a make expert so i could figure out how or why that mkdir without a target is happening.  Probably something easy to fix and the fix would seem to be worth being able to say this tool supports v11+.  But again, it does everything its supposed to do even with the error.

**Comment by MichaelDBA** [comment]
I updated my distro, yum update.  Ran the make install again for versions 11,12 13 and this time I did not get any make install errors!  Don't ask me why.

Do you think you could now relent and make this tool supportable for versions 11+?  There are tons of folks that wont be on v13 for years.  Tools are very appealing when they support most of the Supported Versions of PG.  I want to convince some of my clients to use this tool for auditing.  But they are on older, but still supported, versions of PG.

**Comment by darora** [comment]
Hey Michael-we're unlikely to take on the burden of officially supporting PG11/12 for this extension at this time.

**Comment by MichaelDBA** [comment]
by the way i am getting that same make install error again, but if do this, it doesnt error out:
`make install USE_PGXS=1 with_llvm=no`
