### ISSUE TITLE
How can I use this extension for foreign tables since primary key constraints are not supported on foreign tables .

### ISSUE THREAD

**Issue by ginjojohny** [supabase/supa_audit#37]
I am working with a schema that have foreign tables which are created by using Oracle FDW . How can I use supa_audit extension with these tables since primary key constraints are not supported on foreign tables . Can you suggest any workarounds for it or is it impossible ?

**Comment by olirice** [comment]
>  Can you suggest any workarounds

If you delete these lines:
https://github.com/supabase/supa_audit/blob/c0ea09b9268bac9c6830846a029d3a5d1f4f7594/supa_audit--0.2.3.sql#L242-L244

it will work for tables without a primary key

But be aware that if you do make that change, `record_id`  and `old_record_id` will become random uuids so querying for changes to a given record over time would require querying into the jsonb columns

**Comment by ginjojohny** [comment]
@olirice .Thank you for your suggestion. Will try it out and let you know.  My another question is that is there any way to audit the  column wise details  ie,  to store the details of each column  from the table  which includes  column name , old value and new value  for  any insert/update ( sub table for the record_version )  .

**Comment by olirice** [comment]
>  to store the details of each column from the table which includes column name , old value and new value for any insert/update ( sub table for the record_version ) 

supa_audit does not provide tooling for that kind of representation but you can compute it from the existing representation using [json_each](https://www.postgresql.org/docs/current/functions-json.html) 

Example:
```sql
  create table public.members(
      id int primary key,
      name text not null
  );

  select audit.enable_tracking('public.members');

  insert into public.members(id, name)
  values (1, 'foo');

  update public.members
      set name = 'bar'
      where id = 1;

  select
      arv.id as version_id,
      table_schema,
      table_name,
      arv.op,
      record_id,
      nrec.k as column_name,
      nrec.v as new_value,
      orec.v as old_value,
      ts
  from
      audit.record_version arv,
      lateral(
          select k, v
          from jsonb_each(arv.record) x(k, v)
      ) nrec,
      lateral(
          select k, v
          from jsonb_each(arv.old_record) x(k, v)
      ) orec
  where
      arv.op = 'UPDATE'
      and nrec.k = orec.k;
```

```markdown
version_id | table_schema | table_name |   op   |              record_id               | column_name | new_value | old_value |                 ts                  
------------+--------------+------------+--------+--------------------------------------+-------------+-----------+-----------+-------------------------------------
          2 | public       | members    | UPDATE | 1f955864-dbad-5ae4-be81-ab8b8ac23daa | id          | 1         | 1         | Thu Apr 28 03:34:02.160098 2022 PDT
          2 | public       | members    | UPDATE | 1f955864-dbad-5ae4-be81-ab8b8ac23daa | name        | "bar"     | "foo"     | Thu Apr 28 03:34:02.160098 2022 PDT
(2 rows)
```

**Comment by ginjojohny** [comment]
@olirice Thank you . I will try these workarounds and let you know .
