### ISSUE TITLE
Enable auditing, but ignore specific columns

### ISSUE THREAD

**Issue by dewey** [supabase/supa_audit#41]
# Feature request

## Is your feature request related to a problem? Please describe.

Right now every update on a row will get cause a new record in the record_version table. There are certain columns I would want to exclude from the trigger. In my case that's a "last_fetched_at" column which is more of a debug information than something that has to be audited. I could also see it being useful for sensitive information that you maybe don't want to have replicated in multiple places.

## Describe the solution you'd like

When enabling the tracking on a table (`select audit.enable_tracking('public.users'::regclass);` we could pass a list of columns that should be included or excluded (To be decided what makes more sense). If it would be decided that we could provide a list of columns to ignore it could look like this:

`select audit.enable_tracking('public.users'::regclass, '{last_fetched_at}');`

I'm not sure what's the best way in PG to get the list of columns, and remove the one on the ignore list in the trigger dynamically without a big performance hit in the hot-path. [This looks somehow](https://dba.stackexchange.com/a/307300) useful but I'm not sure if there's a better way.

Do you think something like this would be considered?

**Comment by olirice** [comment]
thanks! I can see how that would add value in some cases but it's beyond the scope we had in mind for the project (which is admittedly pretty limited)

**Comment by dewey** [comment]
I gave this a first shot over here: https://github.com/supabase/supa_audit/pull/42
