### ISSUE TITLE
How can we use this extension when primary key is already in UUID format?

### ISSUE THREAD

**Issue by aiswaryapajit** [supabase/supa_audit#47]
# Bug report

## To Reproduce

Steps to reproduce the behavior, please provide code snippets or a repository:

1. Go to '…'
2. Click on '…'
3. Scroll down to '…'

## System information

- OS: [e.g. macOS, Windows]
- Browser (if applies) [e.g. chrome, safari]
- Version of supabase-js: [e.g. 6.0.2]
- Version of Node.js: [e.g. 10.10.0]

**Comment by aiswaryapajit** [comment]
I got below error when i tried to insert a new data.

SQL Error [42883]: ERROR: function uuid_generate_v4() does not exist
  Hint: No function matches the given name and argument types. You might need to add explicit type casts.
  Where: SQL function "to_record_id" during inlining
SQL statement "SELECT audit.to_record_id(TG_RELID, pkey_cols, record_jsonb)"
PL/pgSQL function audit.insert_update_delete_trigger() line 10 during statement block local variable initialization

**Comment by olirice** [comment]
hi @aiswaryapajit,

there is a detailed description of the problem and a solution in #46

I'm going to close issue but please follow up if you have any trouble getting it to work
