### ISSUE TITLE
Fails on insert in a table when the inserted row is as a result of auth.users trigger 

### ISSUE THREAD

**Issue by kevbook** [supabase/supa_audit#50]
# Bug report

I have a table `public.profiles` that has an insert trigger from `auth.users` table when a new user signs up. This fails when creating a new user using the javascript web package `supabase-js`.

```sql
CREATE TABLE public.profile (
  id uuid NOT NULL REFERENCES auth.users (id),
  avatar_url text NULL,
  PRIMARY KEY ("id")
);

CREATE FUNCTION public.create_profile()
returns TRIGGER AS $$
BEGIN
  INSERT INTO public.profile (id)
  VALUES (new.id);
  return new;
END;
$$ language plpgsql security definer;

CREATE TRIGGER on_auth_user_create AFTER INSERT ON auth.users
  FOR EACH ROW EXECUTE PROCEDURE public.create_profile();

-- enable auditing
SELECT audit.enable_tracking('public.profile'::regclass);
```

## To Reproduce

Using the javascript package `supabase-js`, returns 500 server error `Database error saving new user`. It works when I disable auditing.

**Comment by olirice** [comment]
If you copy/pasted from `supa_audit--0.3.0.sql` to set up the extension the error you are likely running into is 

```
ERROR: function uuid_generate_v4() does not exist (SQLSTATE 42883)
```

you can find an explanation of why that happens, and a solution at https://github.com/supabase/supa_audit/issues/46#issuecomment-1301313938

---

I tested your example above with the solution described ^ and it worked

---

If you are experiencing a different error, please include the error message and any other context that you think might interact
