### ISSUE TITLE
Error when selecting the "Server Error" filter on Auth audit logging

### ISSUE THREAD

**Issue by isley-RealT** [supabase/supa_audit#51]
# Bug report

## To Reproduce

Steps to reproduce the behavior, please provide code snippets or a repository:

1. Go to the Logs section
2. Click on Auth
3. Click on the Status Code dropdown
4. Select Server Error
5. See error: "Sorry! An error occurred when fetching data. `sql parser error: Unterminated string literal at Line: 2, Column 41`"

## Expected behavior

Expected to see Auth audit log

## Screenshots
<img width="1728" alt="image" src="https://user-images.githubusercontent.com/123780489/215296106-13d00854-3ac4-4a0d-a69c-cace81e22ab5.png">

<img width="1728" alt="image" src="https://user-images.githubusercontent.com/123780489/215296128-844f7c22-d4ea-4710-9972-3e740c7c9380.png">

## System information

- OS: macOS
- Browser (if applies) Chrome

**Comment by olirice** [comment]
`supa_audit` is not installed on supabase's platform by default so unless you installed it manually, this error is not related to the `supabase/supa_audit`.

If you did install it manually please re-open this issue and provide some additional context for the SQL statements that led to this error state. e.g. `create table ..., audit.enable..., insert into ...` -> `error in the logs`

That specific error message is saying that someone attempted to execute some invalid SQL. I believe the fact that it says `sql parser error` means that it came supabase studio. 

If you open a support ticket it'll get routed to the right team. They're very responsive
https://supabase.com/support
