### ISSUE TITLE
Applying extension via migrations not working for 0.3.1

### ISSUE THREAD

**Issue by jsbrain** [supabase/supa_audit#55]
The statements introduced in `0.3.1` prevent the extension to be automatically added via migrations.

With `0.3.0` I could just create a migration file and add the extensions that way, now with`0.3.1` it fails with the error:

```txt
Error: ERROR: pg_extension_config_dump() can only be called from an SQL script executed by CREATE EXTENSION (SQLSTATE 0A000)
At statement 4: select                                                                    
    pg_catalog.pg_extension_config_dump ('audit.record_version_id_seq','')
Try rerunning the command with --debug to troubleshoot the error.
```

I checked [the pg docs](https://pgpedia.info/p/pg_extension_config_dump.html) but couldn't really make sense of it. Any idea if there is a way to make this work?

**Comment by olirice** [comment]
if you're attempting to install by copy/pasting the SQL, you can omit any function calls to
```
pg_catalog.pg_extension_*
```
as they're not applicable
